### ISSUE TITLE
ValueError (need more than 2 values to unpack)

### ISSUE THREAD

**Issue by matthias1232** [Noles/check_mk_plugins#6]
Hello,

i am using CheckMK 1.6.0p19 and the poseidon Humidity and Water Sensor check does not work anymore.

Its a fresh migrated System to CentOS8

[PROD_SR-walk.txt](https://github.com/Noles/check_mk_plugins/files/5625413/PROD_SR-walk.txt)

![image](https://user-images.githubusercontent.com/5358267/100796215-934fa400-3420-11eb-8a66-7abc7c9c251f.png)

**Comment by Noles** [comment]
Looks like an incompatibility to cmk 1.6. I have no poseidon device anymore to test but I have made an update to use check-mk's `humidity.include`. Hope this helps.

Maybe you could try it and give me some feedback.

**Comment by matthias1232** [comment]
Hello @Noles 

thank you very much and sorry for the delay. I have tested the Patch on customers side and it seems to work well.

Thank you very much for your help. I think you can release a new mkp File.


![image](https://user-images.githubusercontent.com/5358267/105044782-69e9e680-5a67-11eb-99e7-a7ab3234827c.png)
